import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white-100 dark:bg-zinc-900 transition-all duration-700`}>
        <Header />
        <div className='max-w-6xl mx-auto'>
        {children}
        </div>
      </body>
    </html>
  )
}
